jnosql.document.database=hotels

quarkus.devservices.enabled=false
%dev.quarkus.devservices.enabled=false
%dev.quarkus.mongodb.database=hotels
%dev.quarkus.mongodb.credentials.auth-source=admin
%dev.quarkus.mongodb.credentials.username=root
%dev.quarkus.mongodb.credentials.password=example
