jnosql.document.database=hotels

%dev.quarkus.mongodb.location=localhost:27017
%dev.quarkus.mongodb.database=hotels
%dev.quarkus.mongodb.authentication-database=admin
%dev.quarkus.mongodb.username=root
%dev.quarkus.mongodb.password=example
