@startuml

actor Receptionist


Receptionist -> Webpage: Cancel a reservation by checking guests out of a room
activate Webpage
Webpage -> ReservationResources: DELETE /hotels/{number}
activate ReservationResources
Webpage <- ReservationResources: success or error if reservation is not found
deactivate ReservationResources
Receptionist <- Webpage: success or error if reservation is not found
deactivate Webpage

@enduml
