@startuml
actor Receptionist

Receptionist -> Webpage: Create a reservation by checking guests into a room
activate Webpage
Webpage -> HotelResources: PUT /hotels/
activate HotelResources
Webpage <- HotelResources : return the reservation
deactivate HotelResources
Receptionist <- Webpage: return the reservation
deactivate Webpage

@enduml
