@startuml

actor Receptionist


Receptionist -> Webpage: Getting which rooms are currently reserved
activate Webpage
Webpage -> HotelResources: GET /hotels/?page=1&size=10
activate HotelResources
Webpage <- HotelResources: return a paginated list of reserved rooms
deactivate HotelResources
Receptionist <- Webpage: return a paginated list of reserved rooms
deactivate Webpage

@enduml
