@startuml

actor Concierge


Concierge -> Webpage: getting reservation by room number
activate Webpage
Webpage -> HotelResources: GET /hotels/{number}
activate HotelResources
Webpage <- HotelResources: return the reservation if exists
deactivate HotelResources
Concierge <- Webpage: return the reservation if exists
deactivate Webpage

@enduml
